functionsDirectory = "E:\\Downloads\\universal-guard-trust (1)\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "E:\\Downloads\\universal-guard-trust (1)\\dist"
publishOrigin = "ui"
commandOrigin = "config"
command = "npm run build"
functions = "E:\\Downloads\\universal-guard-trust (1)\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run start:api"
functions = "netlify/functions"

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]